---
title: "SCA_Satellite_SampleExploration"
author: "Zhehan"
date: "November 5, 2019"
output: html_document
---

#Package
```{r}
library(rgdal)
library(raster)
library(qdapRegex)
library(readxl)
library(XML)
library(plyr)
library(dplyr)
library(ggplot2)
```

#Convert kmz to shapefiles 
```{r}
path_sample <- "C:/Users/tangz/Box Sync/sorghum_honduras/Field_BNDs"
#path_sample <- "C:/Users/zt92/Box Sync/sorghum_honduras/Field_BNDs"
#List all kmz files
kmzsample_list <- list.files(path_sample, pattern = "*.kmz", recursive = TRUE, full.names = TRUE)
kmzsample_list
#change the extension from .kmz to .zip
zipsample_list <- gsub(".kmz$", ".zip", kmzsample_list)
names_list <- qdapRegex::ex_between(zipsample_list, left = "Field_BNDs/",right = ".zip")
#Rename them to .zip file 
file.rename(from = kmzsample_list, zipsample_list)
#unzip them
for(i in 1:length(zipsample_list)){
  unzip(zipsample_list[i], exdir = path_sample)
  print(zipsample_list[i])
  file.rename(from = paste0(path_sample,"/Share.kml"), to = paste0(path_sample,"/",names_list[[i]],".kml"))
}

#read kml files 
kmlsample_list <- list.files(path_sample, pattern = "*.kml", recursive = TRUE, full.names = TRUE)
kmlsample_list

#readOGR and write to shapefiles 
#path_sample_shp <- "C:/Users/zt92/Box Sync/sorghum_hondurus/Field_BNDs/shapefiles"
path_sample_shp <- "C:/Users/tangz/Box Sync/sorghum_honduras/Field_BNDs/shapefiles"
for(i in 1:length(kmlsample_list)){
  #read with readOGR
  shp <- readOGR(dsn = kmlsample_list[i])
  #write the shapefiles
  shapefile(shp, file.path(path_sample_shp, paste0(names_list[i],".shp")))
}

#combine shapefiles 
shpsample_list <- list.files(path_sample_shp, pattern = "*.shp", full.names = TRUE)
shpsample_list
#keep only the names 
shpsample_names <- unlist(rm_between(shpsample_list, left = "shapefiles/", right = ".shp", extract = TRUE))
shpsample_names 

#delete kmz files that only have points 
##281001 and 109002 are points 
shpsample_list <- shpsample_list[-c(13,33)]

#an empty list to store shapefiles 
ls_shps <- list()
#store all shapefiles in a list
for(i in 1:length(shpsample_list)){
  ls_shps[[i]] <- shapefile(shpsample_list[i])
  names(ls_shps)[i] <- names_list[[i]]
}



#bind them together 
shpall <- shapefile(shpsample_list[1])
for(i in 2:length(shpsample_list)){
  shp <- shapefile(shpsample_list[i])
  shpall <- raster::bind(shpall, shp)
}
#a simplified version of shpall for GEE
shpall_gee <- shpall
shpall_gee@data <- data.frame("ID" = shpsample_names)
shpall_gee

#find the maximum and minimum extent
shpall_bnd <- as(extent(shpall),"SpatialPolygons")
crs(shpall_bnd) <- crs(shpall)
#output the bnd as a new shapefile
#path_gis <- "C:/Users/zt92/Box Sync/sorghum_hondurus/GIS"
path_gis <- "C:/Users/tangz/Box Sync/sorghum_honduras/GIS"
shapefile(shpall_bnd, file.path(path_gis, "shpall_bnd.shp"), overwrite = TRUE)
shapefile(shpall, file.path(path_gis, "shpall.shp"), overwrite = TRUE)
shapefile(shpall_gee, file.path(path_gis, "shpall_gee.shp"))

plot(shpall, col = "red")
plot(shpall_bnd, add = TRUE)



```
###Create a boundary that covers the field 
```{r}
ls_shpout <- list()
for(i in 1:length(ls_shps)){
  #outer boundary 
  shpout <- as(extent(ls_shps[[i]]),"SpatialPolygons")
  crs(shpout) <- crs(ls_shps[[i]])
  ls_shpout[[i]] <- shpout 
}
#add name 
names(ls_shpout) <- names(ls_shps)

# have a test
plot(ls_shpout[[1]])
plot(ls_shps[[1]], add = TRUE)

```


#Planetscope Surface Reflectance
##do this in Server
```{r}
path_plsr <- "/z0/zt92/sorghum_hondurus/Planetscope_SR"
plsrmeta_ls <- as.list(list.files(path_plsr, pattern = "xml"))
#list of all udm files
plsrudm_ls <- as.list(list.files(path_plsr, pattern = "udm"))  
length(plsrmeta_ls)
length(plsrudm_ls)
#list of all sr files
plsr_ls <- as.list(list.files(path_plsr, pattern = "sr"))
length(plsr_ls)
#there're less sr files than udm and metadata files 

#find out the ones that have the same name
name_srmeta <- sapply(plsrmeta_ls, function(x){rm_between(x, "","_analytic", extract = TRUE)[[1]][1]})
df_srmeta <- data.frame("names" = name_srmeta, "files.meta" = list.files(path_plsr, pattern = "xml", full.names = TRUE))
name_srudm <- sapply(plsrudm_ls, function(x){rm_between(x, "","_udm", extract = TRUE)[[1]][1]})
df_srudm <- data.frame("names" = name_srudm, "files.udm" = list.files(path_plsr, pattern = "udm", full.names = TRUE))
identical(name_srmeta, name_srudm)
#merge meta and udm, because there're less meta than udm 
df_metaudm <- merge(df_srmeta, df_srudm, by = "names")

name_sr <- sapply(plsr_ls, function(x){rm_between(x, "","_analytic", extract = TRUE)[[1]][1]}) 
df_srimg <- data.frame("names" = name_sr, "files.sr" = list.files(path_plsr, pattern = "sr", full.names = TRUE))

df_sr <- merge(df_srimg, df_metaudm, by = "names")
dim(df_sr)
head(df_sr)

#find the dates 
df_sr$Date <- sapply(df_sr$names, function(x){rm_between(x,"","_",extract = TRUE)[[1]][1]})
str(df_sr)

#change class
df_sr$names <- as.character(df_sr$names)
df_sr$files.sr <- as.character(df_sr$files.sr)
df_sr$files.meta <- as.character(df_sr$files.meta)
df_sr$files.udm <- as.character(df_sr$files.udm)

#write the dataframe 
path_df <- "/z0/zt92/sorghum_hondurus/Dataframes"
write.csv(df_sr, file.path(path_df, "df_sr.csv"), row.names = FALSE)
```

##filter by udm 
###Create subset folder
```{r}
#path to store subset 
path_plsr_sb <- "/z0/zt92/sorghum_hondurus/Planetscope_SR_subset"
for(i in 1:length(ls_shpout)){
  dir.create(path = paste(path_plsr_sb, names(ls_shpout)[i],sep = "/"))
}

#list of the subset folders 
ls_sbfolders <- list.files(path_plsr_sb, full.names = TRUE)
```

###Filter with udm   
```{r}
#empty list to store the clean df for each location 
ls_df_clean <- replicate(length(ls_shpout), data.frame(), simplify = FALSE)

#for loop to go through every shapefile 
start_time <- Sys.time()
for(i in 1:length(ls_shpout)){
  #go through every available udm 
  for(j in 1:dim(df_sr)[1]){
    #read udm 
    udm <- raster(df_sr$files.udm[j])
    udm_ext <- extract(udm, ls_shpout[[i]], fun = sum, df = TRUE)
    if(dim(udm_ext)[1]!=0){
      if(udm_ext[,2]==0){
        ls_df_clean[[i]] <- rbind(ls_df_clean[[i]], df_sr[j,])
        print(udm_ext)
      }
    }
    print(df_sr$Date[j])
  }
}
end_time <- Sys.time()
end_time - start_time

#it runs for 2 hours 
```

###Read the sr data, crop to shapefile, extract the reflectance
```{r}
start_time <- Sys.time()

#empty list to store the data
ls_sr_mean <- replicate(length(ls_shpout), data.frame(), simplify = FALSE)

for(i in 1:length(ls_df_clean)){
  for(j in 1:dim(ls_df_clean[[i]])[1]){
    #read files 
    img <- raster::brick(ls_df_clean[[i]]$files.sr[j])
    #crop to a small area
    shpout <- spTransform(ls_shpout[[i]], crs(img))
    img_crop <- raster::crop(img, shpout)
    #write the cropped raster
    writeRaster(img_crop, file.path(ls_sbfolders[i], paste(ls_df_clean[[i]]$names[j], "subset.tif",sep = "_")))
    
    #extract the average reflectance of each band for all fields 
    shp <- spTransform(ls_shps[[i]], crs(img))
    img_ext <- raster::extract(img_crop, shp, na.rm = TRUE, buffer = 0, df = TRUE, fun = mean)
    names(img_ext) <- c("Field","B1","B2","B3","B4")
    img_ext$Field <- names(ls_shps[i])
    #scale factor is 10,000
    img_ext$B1 <- img_ext$B1/10000
    img_ext$B2 <- img_ext$B2/10000
    img_ext$B3 <- img_ext$B3/10000
    img_ext$B4 <- img_ext$B4/10000
    #add dates 
    img_ext$Date <- ls_df_clean[[i]]$Date[j]
    #add file names 
    img_ext$Filename <- ls_df_clean[[i]]$names[j]
    #add the data frame to existing data frame 
    ls_sr_mean[[i]] <- rbind(ls_sr_mean[[i]], img_ext)
    #print to check the progress
    print(ls_df_clean[[i]]$names[j])
    
  }
}

end_time <- Sys.time()
end_time - start_time
#this runs for 12 minutes

#output 
names(ls_sr_mean) <- names(ls_shps)
df_sr_mean <- do.call(rbind, ls_sr_mean)
write.csv(df_sr_mean, file.path(path_df, "df_sr_mean.csv"), row.names = FALSE)
```


#Vegetation Indices for each field 
##do this in local computer
##read dataframe
```{r}
path_localdf <- "C:/Users/zt92/Box Sync/sorghum_hondurus/Dataframes"
df_sr_mean <- read.csv(file.path(path_localdf, "df_sr_mean.csv"))
head(df_sr_mean)
str(df_sr_mean)
#change date format
df_sr_mean$Date <- as.Date(as.character(df_sr_mean$Date), "%Y%m%d")

#merge with class 
##SCA severity
SCA_severity <- read_excel(file.path(path_localdf, "SCA_severity.xlsx"))
str(SCA_severity)
names(SCA_severity)[1] <- "Field"
SCA_severity$Field <- as.factor(SCA_severity$Field)
SCA_severity$Class <- as.factor(SCA_severity$Class)
SCA_severity$No.Class <- as.factor(SCA_severity$No.Class)
SCA_severity[17,]
##merge 
dim(df_sr_mean)
df_sr_mean <- base::merge(df_sr_mean, SCA_severity, by = "Field")
```
##Calculate VIs
```{r}
#ndvi
df_sr_mean <- df_sr_mean %>% dplyr::mutate(NDVI = (B4-B3)/(B4+B3))

```
##Time series plot 
```{r}
ggplot(df_sr_mean, aes(x = Date, y = NDVI, group = Field)) + geom_point(aes(color = Class)) + geom_line(aes(color = Class))

#different classes 
##Healthy
par(mfrow = c(2,3))
srmean_sb <- subset(df_sr_mean, Class == "healthy crop")
fid <- unique(srmean_sb$Field)
for(i in 1:5){
  srmean_sb_sb <- subset(srmean_sb, Field == fid[i])
  plot(x = srmean_sb_sb$Date, y = srmean_sb_sb$NDVI, col = "forestgreen", xlab = "Date", ylab = "NDVI from PL", main = unique(srmean_sb_sb$Field), xlim = c(as.Date("2019-05-01"), as.Date("2019-10-10")), ylim = c(0, 0.8))
}

##SCA infestation 1-25%
par(mfrow = c(2,3))
srmean_sb <- subset(df_sr_mean, Class == "SCA infestation 1-25%")
fid <- unique(srmean_sb$Field)
for(i in 1:5){
  srmean_sb_sb <- subset(srmean_sb, Field == fid[i])
  plot(x = srmean_sb_sb$Date, y = srmean_sb_sb$NDVI, col = "yellow3", xlab = "Date", ylab = "NDVI from PL", main = unique(srmean_sb_sb$Field), xlim = c(as.Date("2019-05-01"), as.Date("2019-10-10")), ylim = c(0, 0.8))
}

##SCA infestation 26-50%
par(mfrow = c(2,3))
srmean_sb <- subset(df_sr_mean, Class == "SCA infestation 26-50%")
fid <- unique(srmean_sb$Field)
for(i in 1:5){
  srmean_sb_sb <- subset(srmean_sb, Field == fid[i])
  plot(x = srmean_sb_sb$Date, y = srmean_sb_sb$NDVI, col = "chocolate1", xlab = "Date", ylab = "NDVI from PL", main = unique(srmean_sb_sb$Field), xlim = c(as.Date("2019-05-01"), as.Date("2019-10-10")), ylim = c(0, 0.8))
}

##SCA infestation 51-75%
par(mfrow = c(2,3))
srmean_sb <- subset(df_sr_mean, Class == "SCA infestation 51-75%")
fid <- unique(srmean_sb$Field)
for(i in 1:5){
  srmean_sb_sb <- subset(srmean_sb, Field == fid[i])
  plot(x = srmean_sb_sb$Date, y = srmean_sb_sb$NDVI, col = "brown1", xlab = "Date", ylab = "NDVI from PL", main = unique(srmean_sb_sb$Field), xlim = c(as.Date("2019-05-01"), as.Date("2019-10-10")), ylim = c(0, 0.8))
}

##SCA infestation 76-100%
par(mfrow = c(2,3))
srmean_sb <- subset(df_sr_mean, Class == "SCA infestation 76-100%")
fid <- unique(srmean_sb$Field)
for(i in 1:5){
  srmean_sb_sb <- subset(srmean_sb, Field == fid[i])
  plot(x = srmean_sb_sb$Date, y = srmean_sb_sb$NDVI, col = "black", xlab = "Date", ylab = "NDVI from PL", main = unique(srmean_sb_sb$Field), xlim = c(as.Date("2019-05-01"), as.Date("2019-10-10")), ylim = c(0, 0.8))
}




```

