---
title: "SCA_sorghumonly"
author: "Zhehan"
date: "March 3, 2020"
output: html_document
---

#Package
```{r}
library(rgdal)
library(raster)
library(rlist)
library(qdapRegex)
library(readxl)
library(XML)
library(plyr)
library(dplyr)
library(ggplot2)
library(lubridate)
```

#Convert kmz to shapefile
```{r}
path_sample <- "C:/Users/zt92/Box Sync/sorghum_honduras/Field_BNDs_sorghumonly"
#path_sample <- "C:/Users/tangz/Box Sync/sorghum_honduras/Field_BNDs"
#path_sample <- "C:/Users/zt92/Box Sync/sorghum_honduras/Field_BNDs"
#List all kmz files
kmzsample_list <- list.files(path_sample, pattern = "*.kmz", recursive = TRUE, full.names = TRUE)
kmzsample_list
#change the extension from .kmz to .zip
zipsample_list <- gsub(".kmz$", ".zip", kmzsample_list)
names_list <- qdapRegex::ex_between(zipsample_list, left = "Field_BNDs_sorghumonly/",right = ".zip")
#Rename them to .zip file 
file.rename(from = kmzsample_list, zipsample_list)
#unzip them
for(i in 1:length(zipsample_list)){
  unzip(zipsample_list[i], exdir = path_sample)
  print(zipsample_list[i])
  file.rename(from = paste0(path_sample,"/Share.kml"), to = paste0(path_sample,"/",names_list[[i]],".kml"))
}

#read kml files 
kmlsample_list <- list.files(path_sample, pattern = "*.kml", recursive = TRUE, full.names = TRUE)
kmlsample_list

#readOGR and write to shapefiles 
#path_sample_shp <- "C:/Users/zt92/Box Sync/sorghum_hondurus/Field_BNDs/shapefiles"
path_sample_shp <- "C:/Users/zt92/Box Sync/sorghum_honduras/Field_BNDs_sorghumonly/shapefiles"
#path_sample_shp <- "C:/Users/tangz/Box Sync/sorghum_honduras/Field_BNDs_sorghumonly/shapefiles"
for(i in 1:length(kmlsample_list)){
  #read with readOGR
  shp <- readOGR(dsn = kmlsample_list[i])
  #write the shapefiles
  shapefile(shp, file.path(path_sample_shp, paste0(names_list[i],".shp")))
}

#combine shapefiles 
shpsample_list <- list.files(path_sample_shp, pattern = "*.shp", full.names = TRUE)
shpsample_list
#keep only the names 
shpsample_names <- unlist(rm_between(shpsample_list, left = "shapefiles/", right = ".shp", extract = TRUE))
shpsample_names 

#delete kmz files that only have points 
##281001 and 109002 are points 
#shpsample_list <- shpsample_list[-c(13,33)]

#an empty list to store shapefiles 
ls_shps <- list()
#store all shapefiles in a list
for(i in 1:length(shpsample_list)){
  ls_shps[[i]] <- shapefile(shpsample_list[i])
  names(ls_shps)[i] <- names_list[[i]]
}



#bind them together 
shpall <- shapefile(shpsample_list[1])
for(i in 2:length(shpsample_list)){
  shp <- shapefile(shpsample_list[i])
  shpall <- raster::bind(shpall, shp)
}
#a simplified version of shpall for GEE
shpall_gee <- shpall
shpall_gee@data <- data.frame("ID" = shpsample_names)
shpall_gee

#find the maximum and minimum extent
shpall_bnd <- as(extent(shpall),"SpatialPolygons")
crs(shpall_bnd) <- crs(shpall)
#output the bnd as a new shapefile
path_gis <- "C:/Users/zt92/Box Sync/sorghum_honduras/GIS"
#path_gis <- "C:/Users/tangz/Box Sync/sorghum_honduras/GIS"
shapefile(shpall_bnd, file.path(path_gis, "shp_sorghum_bnd_gee.shp"), overwrite = TRUE)
#shapefile(shpall, file.path(path_gis, "shpall.shp"), overwrite = TRUE)
shapefile(shpall_gee, file.path(path_gis, "shp_sorghum_gee.shp"))

plot(shpall, col = "red")
plot(shpall_bnd, add = TRUE)
```

###Area distribution 
```{r}
par(mfrow = c(1,1))
hist(area(shpall))
summary(area(shpall))
summary(area(shpall_gee))

```

###Create a boundary that covers the field 
```{r}
ls_shpout <- list()
for(i in 1:length(ls_shps)){
  #outer boundary 
  shpout <- as(extent(ls_shps[[i]]),"SpatialPolygons")
  crs(shpout) <- crs(ls_shps[[i]])
  ls_shpout[[i]] <- shpout 
}
#add name 
names(ls_shpout) <- names(ls_shps)

# have a test
plot(ls_shpout[[1]])
plot(ls_shps[[1]], add = TRUE)
```

#GEE Sentinel
##New sorghum only data: Read NDVI and GNDVI mean data
```{r}
path_gee <- "C:/Users/zt92/Box Sync/sorghum_honduras/GEE"

#NDVI average
S2_CM_NDVI <- read.csv(file.path(path_gee, "S2_CM_sorghum_NDVI_20170101_20200101.csv"))
S2_CM_NDVI <- S2_CM_NDVI[,c("ID","imageId","mean")]
names(S2_CM_NDVI) <- c("ID","Date","NDVI")
S2_CM_NDVI$Date <- as.Date(sapply(rm_between(S2_CM_NDVI$Date, left = "", right = "T", extract = TRUE), '[',1), "%Y%m%d")
head(S2_CM_NDVI)

#GNDVI average
S2_CM_GNDVI <- read.csv(file.path(path_gee, "S2_CM_sorghum_GNDVI_20170101_20200101.csv"))
S2_CM_GNDVI <- S2_CM_GNDVI[,c("ID","imageId","mean")]
names(S2_CM_GNDVI) <- c("ID","Date","GNDVI")
S2_CM_GNDVI$Date <- as.Date(sapply(rm_between(S2_CM_GNDVI$Date, left = "", right = "T", extract = TRUE), '[',1), "%Y%m%d")
head(S2_CM_GNDVI)

#SIPI average
S2_CM_SIPI <- read.csv(file.path(path_gee, "S2_CM_sorghum_SIPI_20170101_20200101.csv"))
S2_CM_SIPI <- S2_CM_SIPI[,c("ID","imageId","mean")]
names(S2_CM_SIPI) <- c("ID","Date","SIPI")
S2_CM_SIPI$Date <- as.Date(sapply(rm_between(S2_CM_SIPI$Date, left = "", right = "T", extract = TRUE), '[',1), "%Y%m%d")
head(S2_CM_SIPI)

#SIPI average
S2_CM_GCL <- read.csv(file.path(path_gee, "S2_CM_sorghum_GCL_20170101_20200101.csv"))
S2_CM_GCL <- S2_CM_GCL[,c("ID","imageId","mean")]
names(S2_CM_GCL) <- c("ID","Date","GCL")
S2_CM_GCL$Date <- as.Date(sapply(rm_between(S2_CM_GCL$Date, left = "", right = "T", extract = TRUE), '[',1), "%Y%m%d")
head(S2_CM_GCL)
```


#Ground Truth data
##New sorghum only data
```{r}
path_raw <- "C:/Users/zt92/Box Sync/Mapping SCA of Sorghum in Honduras/data/sample for exploration"
healthy <- list.files(file.path(path_raw, "healthy crop"))
healthy <- data.frame("Class" = "Healthy", ID = sapply(strsplit(healthy, ".kmz"),"[",1))
healthy
sca_1_25 <- list.files(file.path(path_raw, "SCA infestation 1-25%"))
sca_1_25 <- data.frame("Class" = "SCA 1-25%", ID = sapply(strsplit(sca_1_25, ".kmz"), "[", 1))
sca_1_25
sca_26_50 <- list.files(file.path(path_raw, "SCA infestation 26-50%"))
sca_26_50 <- data.frame("Class" = "SCA 26-50%", ID = sapply(strsplit(sca_26_50, ".kmz"), "[", 1))
sca_26_50
sca_51_75 <- list.files(file.path(path_raw, "SCA infestation 51-75%"))
sca_51_75 <- data.frame("Class" = "SCA 51-75%", ID = sapply(strsplit(sca_51_75, ".kmz"), "[", 1))
sca_51_75
sca_76_100 <- list.files(file.path(path_raw, "SCA infestation 76-100%"))
sca_76_100 <- data.frame("Class" = "SCA 76-100%", ID = sapply(strsplit(sca_76_100, ".kmz"), "[", 1))
sca_76_100
#combine them together 
severity <- rbind(healthy, sca_1_25, sca_26_50, sca_51_75, sca_76_100)
dim(severity)
str(severity)
#merge with the ndvi and gndvi data
S2_CM_NDVI <- merge(S2_CM_NDVI,severity, by = "ID")
S2_CM_GNDVI <- merge(S2_CM_GNDVI, severity, by = "ID")
S2_CM_GCL <- merge(S2_CM_GCL, severity, by = "ID")
S2_CM_SIPI <- merge(S2_CM_SIPI, severity, by =  "ID")

```
##Merge and output
```{r}
dim(S2_CM_NDVI);dim(S2_CM_GNDVI);dim(S2_CM_GCL);dim(S2_CM_SIPI)

S2_CM <- cbind(S2_CM_NDVI, S2_CM_GNDVI$GNDVI, S2_CM_SIPI$SIPI, S2_CM_GCL$GCL)
names(S2_CM)[5:7] <- c("GNDVI","SIPI","GCL")
dim(S2_CM)
head(S2_CM)
 
#output
path_df <- "C:/Users/zt92/Box Sync/sorghum_honduras/Dataframes/sorghum_only"
write.csv(S2_CM, file.path(path_df, "S2_CM.csv"),row.names = FALSE)
```


#Plot time series data 
##New sorghum only data (2017-2019)
###NDVI
```{r}
par(mfrow = c(5,5), mar = c(2,1,2,1))
ls_S2_CM_NDVI <- split(S2_CM_NDVI, S2_CM_NDVI$ID)
severity_color <- unique(S2_CM_NDVI$Class)
for(i in 1:length(ls_S2_CM_NDVI)){
  ls_S2_CM_NDVI[[i]]$Class
  plot(x = ls_S2_CM_NDVI[[i]]$Date, y = ls_S2_CM_NDVI[[i]]$NDVI, main = paste(unique(ls_S2_CM_NDVI[[i]]$ID), unique(ls_S2_CM_NDVI[[i]]$Class), sep = " "), ylab =  "NDVI", col = which(severity_color==unique(ls_S2_CM_NDVI[[i]]$Class)), pch = 20,xlab = "", sub = "", ylim = c(0, 1), xaxt="n")
  axis.Date(1, at = seq(min(ls_S2_CM_NDVI[[i]]$Date), max(ls_S2_CM_NDVI[[i]]$Date), by = "6 mon"), format = "%Y-%m")
}


```
###GNDVI
```{r}
par(mfrow = c(5,5), mar = c(2,1,2,1))
ls_S2_CM_GNDVI <- split(S2_CM_GNDVI, S2_CM_GNDVI$ID)
severity_color <- unique(S2_CM_GNDVI$Class)
for(i in 1:length(ls_S2_CM_GNDVI)){
  plot(x = ls_S2_CM_GNDVI[[i]]$Date, y = ls_S2_CM_GNDVI[[i]]$GNDVI, main = paste(unique(ls_S2_CM_GNDVI[[i]]$ID), unique(ls_S2_CM_GNDVI[[i]]$Class), sep = " "), ylab =  "GNDVI", col = which(severity_color==unique(ls_S2_CM_GNDVI[[i]]$Class)), pch = 20,xlab = "", sub = "", ylim = c(0, 0.8), xaxt="n")
  axis.Date(1, at = seq(min(ls_S2_CM_GNDVI[[i]]$Date), max(ls_S2_CM_GNDVI[[i]]$Date), by = "6 mon"), format = "%Y-%m")
}

```
###SIPI
```{r}
par(mfrow = c(5,5), mar = c(2,1,2,1))
ls_S2_CM_SIPI <- split(S2_CM_SIPI, S2_CM_SIPI$ID)
severity_color <- unique(S2_CM_SIPI$Class)
for(i in 1:length(ls_S2_CM_SIPI)){
  plot(x = ls_S2_CM_SIPI[[i]]$Date, y = ls_S2_CM_SIPI[[i]]$SIPI, main = paste(unique(ls_S2_CM_SIPI[[i]]$ID), unique(ls_S2_CM_SIPI[[i]]$Class), sep = " "), ylab =  "SIPI", col = which(severity_color==unique(ls_S2_CM_SIPI[[i]]$Class)), pch = 20,xlab = "", sub = "", xaxt="n")
  axis.Date(1, at = seq(min(ls_S2_CM_SIPI[[i]]$Date), max(ls_S2_CM_SIPI[[i]]$Date), by = "6 mon"), format = "%Y-%m")
}

```
###GCL
```{r}
par(mfrow = c(5,5), mar = c(2,1,2,1))
ls_S2_CM_GCL <- split(S2_CM_GCL, S2_CM_GCL$ID)
severity_color <- unique(S2_CM_GCL$Class)
for(i in 1:length(ls_S2_CM_GCL)){
  plot(x = ls_S2_CM_GCL[[i]]$Date, y = ls_S2_CM_GCL[[i]]$GCL, main = paste(unique(ls_S2_CM_GCL[[i]]$ID), unique(ls_S2_CM_GCL[[i]]$Class), sep = " "), ylab =  "GCL", col = which(severity_color==unique(ls_S2_CM_GCL[[i]]$Class)), pch = 20,xlab = "", sub = "",  xaxt="n")
  axis.Date(1, at = seq(min(ls_S2_CM_GCL[[i]]$Date), max(ls_S2_CM_GCL[[i]]$Date), by = "6 mon"), format = "%Y-%m")
}
```

##New sorghum only data (2018 only)
###NDVI
```{r}
###NDVI
par(mfrow = c(5,5), mar = c(2,1,2,1))
ls_S2_CM_NDVI <- split(S2_CM_NDVI, S2_CM_NDVI$ID)
severity_color <- unique(S2_CM_NDVI$Class)
for(i in 1:length(ls_S2_CM_NDVI)){
  temp_df = subset(ls_S2_CM_NDVI[[i]], Date > "2018-01-01" & Date < "2019-02-01")
  plot(x = temp_df$Date, y = temp_df$NDVI, main = paste(unique(temp_df$ID), unique(temp_df$Class), sep = " "), ylab =  "NDVI", col = which(severity_color==unique(temp_df$Class)), pch = 20,xlab = "", sub = "", ylim = c(0, 1), xaxt="n")
  axis.Date(1, at = seq(min(temp_df$Date), max(temp_df$Date), by = "3 mon"), format = "%Y-%m")
}
```
###GNDVI
```{r}
###GNDVI
par(mfrow = c(5,5), mar = c(2,1,2,1))
ls_S2_CM_GNDVI <- split(S2_CM_GNDVI, S2_CM_GNDVI$ID)
severity_color <- unique(S2_CM_GNDVI$Class)
for(i in 1:length(ls_S2_CM_GNDVI)){
  temp_df = subset(ls_S2_CM_GNDVI[[i]], Date > "2018-01-01" & Date < "2019-02-01")
  plot(x = temp_df$Date, y = temp_df$GNDVI, main = paste(unique(temp_df$ID), unique(temp_df$Class), sep = " "), ylab =  "GNDVI", col = which(severity_color==unique(temp_df$Class)), pch = 20,xlab = "", sub = "", ylim = c(0, 0.8), xaxt="n")
  axis.Date(1, at = seq(min(temp_df$Date), max(temp_df$Date), by = "3 mon"), format = "%Y-%m")
}
```
###SIPI
```{r}
###SIPI
par(mfrow = c(5,5), mar = c(2,1,2,1))
ls_S2_CM_SIPI <- split(S2_CM_SIPI, S2_CM_SIPI$ID)
severity_color <- unique(S2_CM_SIPI$Class)
for(i in 1:length(ls_S2_CM_SIPI)){
  temp_df = subset(ls_S2_CM_SIPI[[i]], Date > "2018-01-01" & Date < "2019-02-01")
  plot(x = temp_df$Date, y = temp_df$SIPI, main = paste(unique(temp_df$ID), unique(temp_df$Class), sep = " "), ylab =  "SIPI", col = which(severity_color==unique(temp_df$Class)), pch = 20,xlab = "", sub = "", xaxt="n")
  axis.Date(1, at = seq(min(temp_df$Date), max(temp_df$Date), by = "3 mon"), format = "%Y-%m")
}
```
###GCL
```{r}
###GCL
par(mfrow = c(5,5), mar = c(2,1,2,1))
ls_S2_CM_GCL <- split(S2_CM_GCL, S2_CM_GCL$ID)
severity_color <- unique(S2_CM_GCL$Class)
for(i in 1:length(ls_S2_CM_GCL)){
  temp_df = subset(ls_S2_CM_GCL[[i]], Date > "2018-01-01" & Date < "2019-02-01")
  plot(x = temp_df$Date, y = temp_df$GCL, main = paste(unique(temp_df$ID), unique(temp_df$Class), sep = " "), ylab =  "GCL", col = which(severity_color==unique(temp_df$Class)), pch = 20,xlab = "", sub = "", xaxt="n")
  axis.Date(1, at = seq(min(temp_df$Date), max(temp_df$Date), by = "3 mon"), format = "%Y-%m")
}
```

#Weather data
```{r}
path_weather <- "C:/Users/zt92/Box Sync/sorghum_honduras/Weather"

#precipitation
era5tp <- read.csv(file.path(path_weather, "era5tp_ts.csv"))
era5tp <- era5tp[,c("ID","imageId","mean")]
names(era5tp) <- c("ID","Date","precipitation")
era5tp$Date <- ymd(era5tp$Date)
head(era5tp)
dim(era5tp) #51418

#temperature
era52mt <- read.csv(file.path(path_weather, "era52mt_ts.csv"))
era52mt <- era52mt[,c("ID","imageId","mean")]
names(era52mt) <- c("ID","Date","temperature")
era52mt$Date <- ymd(era52mt$Date)
#convert kelvin to celsius
era52mt$temperature <- era52mt$temperature-273.15
head(era52mt)
dim(era52mt) #51418

#precipitation from CHIRPS
chirpstp <- read.csv(file.path(path_weather, "precip_ts.csv"))
chirpstp <- chirpstp[,c("ID","imageId","mean")]
names(chirpstp) <- c("ID","Date","precipitation")
chirpstp$Date <- ymd(chirpstp$Date)
head(chirpstp)
dim(chirpstp) #51465

#merge 
era5 <- merge(era5tp, era52mt, by = c("ID","Date"))
names(era5)[3] <- "precip_era5"
dim(era5)
weather <- merge(era5, chirpstp, by  =  c("ID","Date"))
head(weather)
names(weather)[5] <- "precip_chirps"

#output
path_df <- "C:/Users/zt92/Box Sync/sorghum_honduras/Dataframes/sorghum_only"
write.csv(weather, file.path(path_df, "weather_sorghum.csv"), row.names = FALSE)
```


